// FrontEnd_Angular/src/app/components/login/login.component.ts
import { Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { TranslationService } from '@app/common/services/translation.service';
import { AuthService } from '@app/common/services/auth.service';
import { showAlert } from '@app/common/shared/helper';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.sass']
})

export class LoginComponent implements OnInit {

  userLanguage: string | null = null;
  goToMainRoute: boolean = false;

  formLgn: FormGroup = new FormGroup({
    username: new FormControl(),
    password: new FormControl()
  });
  
  constructor(private router: Router, private authSrv: AuthService, private formBuilder: FormBuilder, public trans: TranslationService) {
    if (!this.authSrv.isActive()) {
      this.authSrv.logout(false);
    } else {
      this.goToMainRoute = true;
    }
    this.formLgn = this.formBuilder.group({
      username: ['', [
        Validators.required,
        Validators.minLength(1)
      ]],
      password: ['', [
        Validators.required,
        Validators.minLength(1)
      ]]
    });
  }

  ngOnInit(): void {
    this.userLanguage = this.trans.lang();
    if (this.goToMainRoute) {
      this.router.navigate(["/"]);
    }
  }

  onSubmitLogin(): void {
    if (this.formLgn.invalid) {
      let message: string = '';
      const usernameControl = this.formLgn.get('username');
      const passwordControl = this.formLgn.get('password');
      if (usernameControl?.hasError('required') || usernameControl?.hasError('minLength')) {
        message = this.trans.get('theUserIsRequired')
      } else if (passwordControl?.hasError('required') || passwordControl?.hasError('minLength')) {
        message = this.trans.get('thePasswordIsRequired')
      }
      showAlert({
        type: 'error',
        title: 'Error!',
        message: message
      });
    } else {
      this.authSrv.login({
        username: this.formLgn.value.username || '',
        password: this.formLgn.value.password || '',
        remember: '',
        time_zone: '',
        previous: 'login',
        language: this.userLanguage
      }).subscribe({
        next: (resp: any): void => {
          console.log(resp);
          this.router.navigate(["/"]);
        },
        error: (ero: any) => {
          showAlert({
            type: 'error',
            title: 'Error!',
            message: ero.error.message
          });
        },
        complete: () => console.info('Login complete')
      });
    }
  }

}



<main class="w-100 p-3">
    <div class="card">
        <div class="card-body">
            <div class="d-flex flex-column p-0">
                
                <form class="container-fluid"
                      [formGroup]="formLgn"
                      (ngSubmit)="onSubmitLogin()">
                    <div class="row">
                        <div class="col-12 mb-3">
                            <label for="ctrl_text_to_speech" class="form-label">
                                {{ trans.get('user') }}
                            </label>
                            <div class="input-group">
                                <span class="input-group-text material-icons-sharp">
                                    person
                                </span>
                                <input placeholder="{{ trans.get('user') }}"
                                       type="text" class="form-control" autofocus
                                       name="username" formControlName="username" required>
                            </div>
                        </div>
                        <div class="col-12 mb-3">
                            <label for="ctrl_text_to_speech" class="form-label">
                                {{ trans.get('password') }}
                            </label>
                            <div class="input-group">
                                <span class="input-group-text material-icons-sharp">
                                    password
                                </span>
                                <input placeholder="{{ trans.get('password') }}"
                                       type="password" class="form-control"
                                       name="password" formControlName="password" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 text-center">
                            <button type="submit" class="btn btn-dark">
                                <div class="d-flex align-items-center">
                                    <span class="material-icons-sharp me-2">
                                        login
                                    </span>
                                    {{ trans.get('login') }}
                                </div>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

// FrontEnd_React/src/app/components/Login.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AuthService } from '../common/services/Auth.tsx';
import { trans } from '../common/services/Translation.tsx';

const Login = () => {
  const navigate = useNavigate();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const onHandleLogin = async () => {
    // Lanzar peticion para iniciar sesión
    let logRespon = await AuthService.login({
        username: username,
        password: password,
    });
    // Tratar resultado
    if (logRespon.isOk) {
      navigate('/hola-mundo');
    }
  };

  return (
    <>
      <main className="w-100 p-3">
        <div className="card">
          <div className="card-body">
            <div className="d-flex flex-column p-0">
              <form className="container-fluid">
                <div className="row">
                  <div className="col-12 mb-3">
                    <label htmlFor="ctrl_text_to_speech" className="form-label">
                      {trans.user}
                    </label>
                    <div className="input-group">
                      <span className="input-group-text material-icons-sharp">
                        person
                      </span>
                      <input
                        autoFocus
                        type="text"
                        value={username}
                        className="form-control"
                        placeholder={trans.user}
                        onChange={(e) => setUsername((e.target.value || '').trim())}
                        required
                      />
                    </div>
                  </div>
                  <div className="col-12 mb-3">
                    <label htmlFor="ctrl_text_to_speech" className="form-label">
                      {trans.password}
                    </label>
                    <div className="input-group">
                      <span className="input-group-text material-icons-sharp">
                        password
                      </span>
                      <input
                        type="password"
                        value={password}
                        className="form-control"
                        placeholder={trans.password}
                        onChange={(e) => setPassword((e.target.value || '').trim())}
                        required
                      />
                    </div>
                  </div>
                </div>
                <div className="row">
                  <div className="col-12 text-center">
                    <button
                      onClick={onHandleLogin}
                      type="button" className="btn btn-dark">
                      <div className="d-flex align-items-center">
                        <span className="material-icons-sharp me-2">login</span>
                        {trans.login}
                      </div>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Login;
